### ISSUE TITLE
feat: resolve absolute path alias

### ISSUE THREAD

**Issue by Boshen** [web-infra-dev/nodejs_resolver#185]
From https://github.com/web-infra-dev/rspack/issues/2914

```
[questionAbsolutePath]: path.resolve(__dirname, "./src/question.prod.js"),
```

**Comment by bvanjoi** [comment]
I think we should check if the expected result can be achieved in webpack firstly

**Comment by Boshen** [comment]
Apparently we need to make a big change, where we need to add a `JoinRequestPlugin` to handle all external rewrites of a path, handling off to @bvanjoi

**Comment by jmikrut** [comment]
Hey @Boshen and @bvanjoi — just chiming in here to support this work. 

We are looking to implement `rspack` into [Payload](https://payloadcms.com/) as a Webpack replacement. We've got it all wired up and ready to go, but this issue is currently a blocker for us.

If we can get this resolved, `rspack` will get a ton of publicity and downloads. It would be awesome. We love what this team is doing and outside of this one issue, we've had a very smooth migration process!

**Comment by bvanjoi** [comment]
> We are looking to implement rspack into [Payload](https://payloadcms.com/) as a Webpack replacement. We've got it all wired up and ready to go, but this issue is currently a blocker for us.

Glad to hear your feedback. Could you please provide more details about your usage scenario? With that information, I can explore possible temporary workarounds for this feature (since I've been busy lately, I may not be able to implement this immediately).

**Comment by jmikrut** [comment]
Absolutely, wow, I greatly appreciate the speed here.

So, Payload has a "config" that is shared between both the client and the server.

It is responsible for dynamically producing REST API endpoints, GraphQL, etc. etc. 

**It's also used to generate an admin panel** which is where `rspack` comes in. 

The catch is that our config is loaded in both the browser AND the server. And we leverage Webpack aliases to completely replace server-side only modules with mock files, where we need to. 

An unknown variety of server-side modules need to be aliased out, and they are potentially imported from many places throughout a Payload config. 

I've read that a workaround is to just use relative path aliases, but that is not possible for us for a few reasons:

1. We have no way of knowing the relative path of the server-side code to alias (i.e. which file was it imported from?)
2. We have a large, existing community of plugins / etc. that all implement pre-existing absolute aliases

In Webpack, we use absolute paths to any specific files that we need to alias, and this works great. That way no matter where the "file to alias" was imported from, it will be aliased with one single absolute alias.

Does that make any sense? I can talk more to this as well, and would be happy to pair if you want to brainstorm further. Keep me posted!

**Comment by bvanjoi** [comment]
It seems that we have added support for using absolute paths in alias targets. You can find an example of this in the following code snippet: https://github.com/web-infra-dev/nodejs_resolver/blob/main/tests/cases.rs#L338-L348

---

I am unable to reproduce this issue because the repo linked from https://github.com/web-infra-dev/rspack/issues/2914#issuecomment-1550516483 returns a 404.

**Comment by jmikrut** [comment]
I am not well-versed in Rust, but I believe that snippet shows a test for an absolute alias _**target**_ and the original issue is in regards to the lack of support for an absolute  _**source**_.

If I'm reading the snippet right, it tests an alias something like this, right?

```
const aliases = {
  fs: '/some/absolute/path'
}
```

For clarity, I am not talking about the `target` being the issue here. I'm talking about what would be the `source` in this case.

```js
const aliases = {
  // Webpack supports absolute -sources-
  [sourceThatCanBeAbsolute]: [target}
}
```

I am fairly confident this is an issue still. If you need a minimally reproducible repo, I am happy to get one to you.

Please let me know if I am understanding everything correctly here!

**Comment by bvanjoi** [comment]
thanks for that, I had recalled it.

**Comment by hardfist** [comment]
https://github.com/web-infra-dev/rspack-repro/blob/alias-test/config.mjs#L39 tested it here, seems works for absolute path

**Comment by jmikrut** [comment]
@hardfist thank you for the followup!

I just pulled that test down and noticed a few things. First, you are [_**referencing**_ the absolute alias by the exact same absolute path in your source code](https://github.com/web-infra-dev/rspack-repro/blob/alias-test/src/index.js#L1).

This will work just fine. But that's not where the Webpack mismatch comes in.

I've cloned your repro and adjusted it to match a real-world use case. Take a look here:

https://github.com/jmikrut/rspack-absolute-alias

Branch: `alias-test`

Simply run `pnpm run dev:webpack` to see that the console logs `b` appropriately, and then run `pnpm run dev:rspack` to see that the console _still logs_ `a`.

This is the nature of the discrepancy. So I think there is still an issue here.

What do you think?

**Comment by hardfist** [comment]
thanks, i can confirm the mismatch here

**Comment by hardfist** [comment]
@jmikrut we're rewriting the node_resolver module now and it's hard to fix this bug in the old node_resolver module now, please wait for the new node_resolver implementation which will fix this bug, @Boshen please take care this edge case for new implementation

**Comment by hardfist** [comment]
@jmikrut this bug is fixed in new resolver implementation, you can see the result here https://github.com/hardfist/rspack-absolute-alias/blob/fix-alias/config.mjs#L39

**Comment by Boshen** [comment]
This should be fixed in the newest Rspack release via `oxc_resolver` instead of this crate.
